### ISSUE TITLE
Some problem with "ble.recon on"  (kali)

### ISSUE THREAD

**Issue by WilliamL71Oi** [bettercap/bettercap#1095]
» panic: runtime error: slice bounds out of range [2:0]

goroutine 164 [running]:
github.com/bettercap/gatt.(*Advertisement).unmarshall(0xc000179e10, 0xc00055dd40, 0x1a, 0x1a, 0xc00050ae86, 0xc00050aee8)
        /go/pkg/mod/github.com/bettercap/gatt@v0.0.0-20210514133428-df6e615f2f67/adv.go:2013 +0x1465
github.com/bettercap/gatt.(*device).Init.func3(0xc0004caaa0)
        /go/pkg/mod/github.com/bettercap/gatt@v0.0.0-20210514133428-df6e615f2f67/device_linux.go:97 +0x6d
github.com/bettercap/gatt/linux.(*HCI).handleAdvertisement(0xc0006d8000, 0xc000834003, 0x64, 0xffd)
        /go/pkg/mod/github.com/bettercap/gatt@v0.0.0-20210514133428-df6e615f2f67/linux/hci.go:319 +0x4f4
created by github.com/bettercap/gatt/linux.(*HCI).handleLEMeta
        /go/pkg/mod/github.com/bettercap/gatt@v0.0.0-20210514133428-df6e615f2f67/linux/hci.go:432 +0x190

kali:
uname -a
Linux kali 6.6.15-amd64 #1 SMP PREEMPT_DYNAMIC Kali 6.6.15-2kali1 (2024-04-09) x86_64 GNU/Linux

![image](https://github.com/bettercap/bettercap/assets/37209194/afc28457-b83e-4d92-8af0-5281206abeaa)

**Comment by WilliamL71Oi** [comment]
![image](https://github.com/bettercap/bettercap/assets/37209194/6d303439-45dc-48fe-8b74-a51e6968767e)
