### ISSUE TITLE
trying to install buttercup on osx

### ISSUE THREAD

**Issue by Virgula0** [bettercap/bettercap#147]
i have installed go on Mac (go version go1.10 darwin/amd64)

I'm trying to install bettercap on osx (I also installed lib cap with` brew install libpcap`)  and then

`go get github.com/bettercap/bettercap`

but when I try to launch it with `sudo bettercap`:

```
/usr/local/Cellar/ruby21/2.1.10/lib/ruby/2.1.0/rubygems/dependency.rb:298:in `to_specs': Could not find 'bettercap' (>= 0) among 8 total gem(s) (Gem::LoadError)
	from /usr/local/Cellar/ruby21/2.1.10/lib/ruby/2.1.0/rubygems/dependency.rb:309:in `to_spec'
	from /usr/local/Cellar/ruby21/2.1.10/lib/ruby/2.1.0/rubygems/core_ext/kernel_gem.rb:53:in `gem'
	from /Users/user/.rvm/gems/ruby-2.1.9/bin/bettercap:22:in `<main>'
	from /Users/user/.rvm/gems/ruby-2.1.9/bin/ruby_executable_hooks:15:in `eval'
	from /Users/user/.rvm/gems/ruby-2.1.9/bin/ruby_executable_hooks:15:in `<main>'
```

How can I resolve? Thank You

**Comment by evilsocket** [comment]
`sudo gem uninstall bettercap`
