### ISSUE TITLE
Unable to set double HTTP headers

### ISSUE THREAD

**Issue by yungtravla** [bettercap/bettercap#287]
In the HTTP proxy we only have access to the first instance of a header name. For example, even if there are multiple `Set-Cookie` headers, using `res.SetHeader("Set-Cookie", "...")` will only change the first instance.

### Environment

Please provide:

* Bettercap version you are using.
`bettercap v2.6`
* OS version and architecture you are using.
`Linux ghxst 4.15.0-kali2-amd64 #1 SMP Debian 4.15.11-1kali1 (2018-03-21) x86_64 GNU/Linux`
* Go version if building from sources.
`go version go1.10rc2 linux/amd64`
* Command line arguments you are using.
_none_
* Caplet code you are using or the interactive session commands.
_none_
* **Full debug output** while reproducing the issue ( `bettercap -debug ...` ).

_(the following debug output is what happens when you follow the steps to reproduce below)_
```
192.168.12.0/24 > 192.168.12.1  » [08:22:06] [net.sniff.leak.http] http 192.168.12.228 GET www.google.com/ Mozilla/5.0 (Android 6.0.1; Mobile; rv:60.0) Gecko/60.0 Firefox/60.0 
192.168.12.0/24 > 192.168.12.1  » 2018/06/04 08:22:06 http: panic serving 192.168.12.228:39974: reflect: reflect.Value.Set using unaddressable value
goroutine 45 [running]:
net/http.(*conn).serve.func1(0xc4222ac0a0)
	/usr/lib/go-1.10/src/net/http/server.go:1726 +0xd0
panic(0xd812c0, 0xc4221163c0)
	/usr/lib/go-1.10/src/runtime/panic.go:505 +0x229
github.com/bettercap/bettercap/vendor/github.com/robertkrimen/otto.catchPanic.func1(0xc421efd5d0)
	/root/go/src/github.com/bettercap/bettercap/vendor/github.com/robertkrimen/otto/error.go:248 +0x536
panic(0xd812c0, 0xc4221163c0)
	/usr/lib/go-1.10/src/runtime/panic.go:505 +0x229
reflect.flag.mustBeAssignable(0x98)
	/usr/lib/go-1.10/src/reflect/value.go:234 +0x15c
reflect.Value.Set(0xd812c0, 0xc421bf1df0, 0x98, 0xd812c0, 0xc4221163b0, 0x98)
	/usr/lib/go-1.10/src/reflect/value.go:1367 +0x2f
github.com/bettercap/bettercap/vendor/github.com/robertkrimen/otto._goStructObject.setValue(0xdf6720, 0xc421bf1de0, 0x99, 0xc421444d51, 0x5, 0x3, 0xd812c0, 0xc420d77d80, 0xf75371fa21efbd10)
	/root/go/src/github.com/bettercap/bettercap/vendor/github.com/robertkrimen/otto/type_go_struct.go:71 +0x23f
github.com/bettercap/bettercap/vendor/github.com/robertkrimen/otto.goStructPut(0xc421907200, 0xc421444d51, 0x5, 0x3, 0xd812c0, 0xc420d77d80, 0xdf1600)
	/root/go/src/github.com/bettercap/bettercap/vendor/github.com/robertkrimen/otto/type_go_struct.go:131 +0x91
github.com/bettercap/bettercap/vendor/github.com/robertkrimen/otto.(*_object).put(0xc421907200, 0xc421444d51, 0x5, 0x3, 0xd812c0, 0xc420d77d80, 0xde9400)
	/root/go/src/github.com/bettercap/bettercap/vendor/github.com/robertkrimen/otto/object.go:52 +0x6e
github.com/bettercap/bettercap/vendor/github.com/robertkrimen/otto.(*_propertyReference).putValue(0xc422d87bf0, 0x3, 0xd812c0, 0xc420d77d80, 0xdf1680, 0xc422d87bf0)
	/root/go/src/github.com/bettercap/bettercap/vendor/github.com/robertkrimen/otto/type_reference.go:45 +0x6f
github.com/bettercap/bettercap/vendor/github.com/robertkrimen/otto.(*_runtime).putValue(0xc42045b200, 0x1003b60, 0xc422d87bf0, 0x3, 0xd812c0, 0xc420d77d80)
	/root/go/src/github.com/bettercap/bettercap/vendor/github.com/robertkrimen/otto/runtime.go:110 +0x56
github.com/bettercap/bettercap/vendor/github.com/robertkrimen/otto.(*_runtime).cmpl_evaluate_nodeAssignExpression(0xc42045b200, 0xc420dfe120, 0xd7fc40, 0xc421cc8ae8, 0xc421efbf20)
	/root/go/src/github.com/bettercap/bettercap/vendor/github.com/robertkrimen/otto/cmpl_evaluate_expression.go:132 +0x163
github.com/bettercap/bettercap/vendor/github.com/robertkrimen/otto.(*_runtime).cmpl_evaluate_nodeExpression(0xc42045b200, 0xff9260, 0xc420dfe120, 0x6, 0xc421bf1d20, 0xc421efbfb8)
	/root/go/src/github.com/bettercap/bettercap/vendor/github.com/robertkrimen/otto/cmpl_evaluate_expression.go:31 +0x626
github.com/bettercap/bettercap/vendor/github.com/robertkrimen/otto.(*_runtime).cmpl_evaluate_nodeStatement(0xc42045b200, 0xff93c0, 0xc420d77d90, 0x0, 0x0, 0x0)
	/root/go/src/github.com/bettercap/bettercap/vendor/github.com/robertkrimen/otto/cmpl_evaluate_statement.go:62 +0xf39
github.com/bettercap/bettercap/vendor/github.com/robertkrimen/otto.(*_runtime).cmpl_evaluate_nodeForStatement(0xc42045b200, 0xc4216bb180, 0x0, 0x0, 0x0)
	/root/go/src/github.com/bettercap/bettercap/vendor/github.com/robertkrimen/otto/cmpl_evaluate_statement.go:263 +0x1de
github.com/bettercap/bettercap/vendor/github.com/robertkrimen/otto.(*_runtime).cmpl_evaluate_nodeStatement(0xc42045b200, 0xff9400, 0xc4216bb180, 0x0, 0x0, 0x0)
	/root/go/src/github.com/bettercap/bettercap/vendor/github.com/robertkrimen/otto/cmpl_evaluate_statement.go:68 +0x1183
github.com/bettercap/bettercap/vendor/github.com/robertkrimen/otto.(*_runtime).cmpl_evaluate_nodeStatementList(0xc42045b200, 0xc420096a80, 0x6, 0x6, 0xbc8b8c, 0xc420086768, 0x72db88)
	/root/go/src/github.com/bettercap/bettercap/vendor/github.com/robertkrimen/otto/cmpl_evaluate_statement.go:121 +0x94
github.com/bettercap/bettercap/vendor/github.com/robertkrimen/otto.(*_runtime).cmpl_evaluate_nodeStatement(0xc42045b200, 0xff92a0, 0xc420dbb9e0, 0x0, 0x0, 0x0)
	/root/go/src/github.com/bettercap/bettercap/vendor/github.com/robertkrimen/otto/cmpl_evaluate_statement.go:30 +0x5d6
github.com/bettercap/bettercap/vendor/github.com/robertkrimen/otto.(*_runtime).cmpl_call_nodeFunction(0xc42045b200, 0xc420097b60, 0xc421d6e2a0, 0xc421446c00, 0x5, 0xe88640, 0xc42147e240, 0xc421d6e270, 0x2, 0x2, ...)
	/root/go/src/github.com/bettercap/bettercap/vendor/github.com/robertkrimen/otto/cmpl_evaluate.go:61 +0x452
github.com/bettercap/bettercap/vendor/github.com/robertkrimen/otto.(*_object).call(0xc420097b60, 0x5, 0xe88640, 0xc42147e240, 0xc421d6e270, 0x2, 0x2, 0x0, 0x0, 0x0, ...)
	/root/go/src/github.com/bettercap/bettercap/vendor/github.com/robertkrimen/otto/type_function.go:226 +0x8a5
github.com/bettercap/bettercap/vendor/github.com/robertkrimen/otto.(*_runtime).cmpl_evaluate_nodeCallExpression(0xc42045b200, 0xc421b65020, 0x0, 0x0, 0x0, 0xc42133f520, 0xc4200872f8, 0xbc81a2)
	/root/go/src/github.com/bettercap/bettercap/vendor/github.com/robertkrimen/otto/cmpl_evaluate_expression.go:244 +0x4ff
github.com/bettercap/bettercap/vendor/github.com/robertkrimen/otto.(*_runtime).cmpl_evaluate_nodeExpression(0xc42045b200, 0xff9300, 0xc421b65020, 0xc421fba100, 0x20, 0x18)
	/root/go/src/github.com/bettercap/bettercap/vendor/github.com/robertkrimen/otto/cmpl_evaluate_expression.go:44 +0x588
github.com/bettercap/bettercap/vendor/github.com/robertkrimen/otto.(*_runtime).cmpl_evaluate_nodeStatement(0xc42045b200, 0xff93c0, 0xc421b74430, 0x0, 0x0, 0x0)
	/root/go/src/github.com/bettercap/bettercap/vendor/github.com/robertkrimen/otto/cmpl_evaluate_statement.go:62 +0xf39
github.com/bettercap/bettercap/vendor/github.com/robertkrimen/otto.(*_runtime).cmpl_evaluate_nodeStatementList(0xc42045b200, 0xc421b74420, 0x1, 0x1, 0xc42145a198, 0xc42145a1a0, 0x5)
	/root/go/src/github.com/bettercap/bettercap/vendor/github.com/robertkrimen/otto/cmpl_evaluate_statement.go:121 +0x94
github.com/bettercap/bettercap/vendor/github.com/robertkrimen/otto.(*_runtime).cmpl_evaluate_nodeProgram(0xc42045b200, 0xc42142bd50, 0x745f00, 0x0, 0x0, 0x0)
	/root/go/src/github.com/bettercap/bettercap/vendor/github.com/robertkrimen/otto/cmpl_evaluate.go:17 +0xe7
github.com/bettercap/bettercap/vendor/github.com/robertkrimen/otto.(*_runtime).cmpl_runOrEval.func1()
	/root/go/src/github.com/bettercap/bettercap/vendor/github.com/robertkrimen/otto/runtime.go:767 +0x44
github.com/bettercap/bettercap/vendor/github.com/robertkrimen/otto.catchPanic(0xc420087638, 0x0, 0x0)
	/root/go/src/github.com/bettercap/bettercap/vendor/github.com/robertkrimen/otto/error.go:251 +0x55
github.com/bettercap/bettercap/vendor/github.com/robertkrimen/otto.(*_runtime).cmpl_runOrEval(0xc42045b200, 0xdd7be0, 0xc42154ec80, 0x0, 0x0, 0xe3bc00, 0xc4216e40c0, 0x0, 0x0, 0xc421463440, ...)
	/root/go/src/github.com/bettercap/bettercap/vendor/github.com/robertkrimen/otto/runtime.go:766 +0x10f
github.com/bettercap/bettercap/vendor/github.com/robertkrimen/otto.(*_runtime).cmpl_run(0xc42045b200, 0xdd7be0, 0xc42154ec80, 0x0, 0x0, 0x745fb9, 0xc400000008, 0xc421463440, 0x10, 0xc42146e740)
	/root/go/src/github.com/bettercap/bettercap/vendor/github.com/robertkrimen/otto/runtime.go:779 +0x62
github.com/bettercap/bettercap/vendor/github.com/robertkrimen/otto.Otto.Run(0x0, 0xc42045b200, 0xdd7be0, 0xc42154ec80, 0xc4216ea0d0, 0xc4216e40c0, 0x7f051c012d90, 0x0, 0x0)
	/root/go/src/github.com/bettercap/bettercap/vendor/github.com/robertkrimen/otto/otto.go:295 +0x4b
github.com/bettercap/bettercap/modules.(*HttpProxyScript).OnRequest(0xc421b61ec0, 0xc4215ee500, 0xc4216ea0d0, 0xc4216e40c0)
	/root/go/src/github.com/bettercap/bettercap/modules/http_proxy_script.go:121 +0x261
github.com/bettercap/bettercap/modules.(*HTTPProxy).onRequestFilter(0xc4213b6480, 0xc4215ee500, 0xc421682190, 0x72d339, 0xc4218de02f)
	/root/go/src/github.com/bettercap/bettercap/modules/http_proxy_base_filters.go:29 +0x276
github.com/bettercap/bettercap/modules.(*HTTPProxy).(github.com/bettercap/bettercap/modules.onRequestFilter)-fm(0xc4215ee500, 0xc421682190, 0x100000000000001, 0x0)
	/root/go/src/github.com/bettercap/bettercap/modules/http_proxy_base.go:82 +0x3e
github.com/bettercap/bettercap/vendor/github.com/elazarl/goproxy.FuncReqHandler.Handle(0xc4213b9cd0, 0xc4215ee500, 0xc421682190, 0x10, 0x10)
	/root/go/src/github.com/bettercap/bettercap/vendor/github.com/elazarl/goproxy/actions.go:19 +0x3a
github.com/bettercap/bettercap/vendor/github.com/elazarl/goproxy.(*ReqProxyConds).Do.func1(0xc4215ee500, 0xc421682190, 0x7f051c012d90, 0x0)
	/root/go/src/github.com/bettercap/bettercap/vendor/github.com/elazarl/goproxy/dispatcher.go:200 +0xe1
github.com/bettercap/bettercap/vendor/github.com/elazarl/goproxy.FuncReqHandler.Handle(0xc4213d78a0, 0xc4215ee500, 0xc421682190, 0x72b26a, 0x10)
	/root/go/src/github.com/bettercap/bettercap/vendor/github.com/elazarl/goproxy/actions.go:19 +0x3a
github.com/bettercap/bettercap/vendor/github.com/elazarl/goproxy.(*ProxyHttpServer).filterRequest(0xc420458700, 0xc4215ee500, 0xc421682190, 0xc42146eb20, 0x4)
	/root/go/src/github.com/bettercap/bettercap/vendor/github.com/elazarl/goproxy/proxy.go:56 +0x92
github.com/bettercap/bettercap/vendor/github.com/elazarl/goproxy.(*ProxyHttpServer).ServeHTTP(0xc420458700, 0x10025e0, 0xc421d940e0, 0xc4215ee500)
	/root/go/src/github.com/bettercap/bettercap/vendor/github.com/elazarl/goproxy/proxy.go:108 +0x298
github.com/bettercap/bettercap/modules.NewHTTPProxy.func1(0x10025e0, 0xc421d940e0, 0xc4215ee500)
	/root/go/src/github.com/bettercap/bettercap/modules/http_proxy_base.go:77 +0xa6
net/http.HandlerFunc.ServeHTTP(0xc4213b9cb0, 0x10025e0, 0xc421d940e0, 0xc4215ee500)
	/usr/lib/go-1.10/src/net/http/server.go:1947 +0x44
github.com/bettercap/bettercap/vendor/github.com/elazarl/goproxy.(*ProxyHttpServer).ServeHTTP(0xc420458700, 0x10025e0, 0xc421d940e0, 0xc4215ee500)
	/root/go/src/github.com/bettercap/bettercap/vendor/github.com/elazarl/goproxy/proxy.go:105 +0x9bd
net/http.serverHandler.ServeHTTP(0xc421740c30, 0x10025e0, 0xc421d940e0, 0xc4215ee500)
	/usr/lib/go-1.10/src/net/http/server.go:2694 +0xbc
net/http.(*conn).serve(0xc4222ac0a0, 0x10032a0, 0xc42145a100)
	/usr/lib/go-1.10/src/net/http/server.go:1830 +0x651
created by net/http.(*Server).Serve
	/usr/lib/go-1.10/src/net/http/server.go:2795 +0x27b

```

### Steps to Reproduce

1. *Save the following code as **issue287.js***
```js
function onRequest(req, res) {
  for (var i = 0; i < req.Headers.length; i++) {
    req.Headers[i].Name  = "Test"
    req.Headers[i].Value = "Test"
  }
}
```
2. *Test the proxy script and see the error.*

**Expected behavior:** We can set multiple headers with the same name. For example, `Set-Cookie` is often used multiple times in a single response packet, but as far as I know we are only able to change the first instance of `Set-Cookie` by using `SetHeader()`.

**Actual behavior:** Even if there are multiple `Set-Cookie` headers, using `res.SetHeader("Set-Cookie", "...")` will only change the first instance.

-- 

**♥ ANY INCOMPLETE REPORT WILL BE CLOSED RIGHT AWAY ♥**

**Comment by yungtravla** [comment]
I was thinking maybe a `req.NewHeader("Set-Cookie", "...")` but that would only let us add headers, not change them.

I think if we can change `req.Headers[i].Name` and `req.Headers[i].Value` values, we can do both.

**Comment by evilsocket** [comment]
> I think if we can change req.Headers[i].Name and req.Headers[i].Value values, we can do both.

can you elaborate with an example of how the implementation you have in mind would work?

**Comment by yungtravla** [comment]
I'm not sure exactly how otto works but I think that if we convert the JSHeader struct to JSON (and back) that we could achieve this.

**Comment by yungtravla** [comment]
@evilsocket i think i now understand why you made the headers in **http_proxy_js_response.go** a string :smile: 

it's probably overkill to import a json library just to handle double headers, and if we turn the headers from a JSHeader struct into a string we can also drop a few lines of code

happy to update all the caplets if you think this is a valid solution :)

**Comment by evilsocket** [comment]
mmm example code of what you mean?

**Comment by yungtravla** [comment]
@evilsocket https://github.com/bettercap/bettercap/commit/8f1bcdfe70904bf71729515004910aa205d27d23#r29306657 `res.Headers` used to return a string and `req.Headers` returns an object.

If we use a string we can split per `\n`, that way we can definitely reach all the headers.

**Comment by evilsocket** [comment]
Great, two questions:

1) Did you test other caplets to see if that broke backwards compatibility?
2) Can this issue be closed?

**Comment by evilsocket** [comment]
@yungtravla ping

**Comment by yungtravla** [comment]
Hey, gonna knock this out now :+1:

**Comment by evilsocket** [comment]
great, thanks! :D
