### ISSUE TITLE
api.rest on fails with panic: read /root: is a directory

### ISSUE THREAD

**Issue by strasharo** [bettercap/bettercap#360]
### Environment

Please provide:

* Bettercap version you are using. - v2.10
* OS version and architecture you are using. - Fedora 28 x64
* Go version if building from sources. - go version go1.10.4 linux/amd64
* Command line arguments you are using.
* Caplet code you are using or the interactive session commands. rest-api.cap fails on api.rest on
* **Full debug output** while reproducing the issue ( `bettercap -debug ...` ).
```
bettercap v2.10 (type 'help' for a list of commands)

192.168.0.0/24 > 192.168.0.4  » [21:25:20] [sys.log] [dbg] FindGateway(wlp2s0) [cmd=ip opts=[route] parser=^(default|[0-9\.]+)\svia\s([0-9\.]+)\sdev\s(\w+)\s.*$]
192.168.0.0/24 > 192.168.0.4  » [21:25:20] [sys.log] [dbg] FindGateway(wlp2s0) output:
default via 192.168.0.1 dev wlp2s0 proto dhcp metric 600 
172.17.0.0/16 dev docker0 proto kernel scope link src 172.17.0.1 linkdown 
192.168.0.0/24 dev wlp2s0 proto kernel scope link src 192.168.0.4 metric 600 
192.168.122.0/24 dev virbr0 proto kernel scope link src 192.168.122.1 linkdown
192.168.0.0/24 > 192.168.0.4  » [21:25:20] [sys.log] [dbg] FindGateway(wlp2s0) line 'default via 192.168.0.1 dev wlp2s0 proto dhcp metric 600' matched with [default via 192.168.0.1 dev wlp2s0 proto dhcp metric 600 default 192.168.0.1 wlp2s0]
192.168.0.0/24 > 192.168.0.4  » [21:25:20] [sys.log] [dbg] gateway is 192.168.0.1[c4:12:f5:00:ce:92]
192.168.0.0/24 > 192.168.0.4  » [21:25:20] [session.started] {session.started 2018-10-13 21:25:20.674572669 +0300 EEST m=+0.050462483 <nil>}
192.168.0.0/24 > 192.168.0.4  » [21:25:20] [mod.started] events.stream
192.168.0.0/24 > 192.168.0.4  » [21:25:20] [mod.started] net.recon
192.168.0.0/24 > 192.168.0.4  » [21:25:20] [endpoint.new] endpoint 192.168.0.6 detected as 00:08:22:26:01:fc (InPro Comm).
192.168.0.0/24 > 192.168.0.4  » [21:25:20] [endpoint.new] endpoint 192.168.0.3 detected as 7c:dd:90:24:31:bc (Shenzhen Ogemray Technology Co., Ltd.).
192.168.0.0/24 > 192.168.0.4  » [21:25:20] [endpoint.new] endpoint 192.168.0.7 detected as 40:e2:30:4e:ac:89 (AzureWave Technology Inc.).
192.168.0.0/24 > 192.168.0.4  » [21:25:20] [endpoint.new] endpoint 192.168.0.5 detected as 00:f1:ff:d7:ee:5b.
192.168.0.0/24 > 192.168.0.4  » rest-api
[21:25:22] [sys.log] [dbg] Throttling packets of 10 ms.
[21:25:22] [mod.started] net.probe
[21:25:22] [sys.log] [inf] loading TLS key from /usr/local/share/bettercap/caplets
[21:25:22] [sys.log] [inf] loading TLS certificate from /usr/local/share/bettercap/caplets
[21:25:22] [sys.log] [dbg] sent 88 bytes of MDNS probe
[21:25:22] [mod.started] api.rest
192.168.0.0/24 > 192.168.0.4  » [21:25:22] [sys.log] [inf] api server starting on https://192.168.0.4:8081
192.168.0.0/24 > 192.168.0.4  » panic: read /usr/local/share/bettercap/caplets: is a directory

goroutine 84 [running]:
github.com/bettercap/bettercap/modules.(*RestAPI).Start.func1()
	/home/v/go/src/github.com/bettercap/bettercap/modules/api_rest.go:218 +0x209
created by github.com/bettercap/bettercap/session.(*SessionModule).SetRunning
	/home/v/go/src/github.com/bettercap/bettercap/session/module.go:160 +0x1a0
```

### Steps to Reproduce

1. Launch bettercap with root
2. set api.rest.username tester
3. set api.rest.password testing
4. api.rest on

**Expected behavior:** *What you expected to happen*
Rest api should launch

**Actual behavior:** *What actually happened*
bettercap terminates with

```
192.168.0.0/24 > 192.168.0.4  » api.rest on
[21:27:41] [sys.log] [inf] loading TLS key from /root
[21:27:41] [sys.log] [inf] loading TLS certificate from /root
192.168.0.0/24 > 192.168.0.4  » [21:27:41] [sys.log] [inf] api server starting on https://192.168.0.4:8081
192.168.0.0/24 > 192.168.0.4  » panic: read /root: is a directory

goroutine 152 [running]:
github.com/bettercap/bettercap/modules.(*RestAPI).Start.func1()
	/home/v/go/src/github.com/bettercap/bettercap/modules/api_rest.go:218 +0x209
created by github.com/bettercap/bettercap/session.(*SessionModule).SetRunning
	/home/v/go/src/github.com/bettercap/bettercap/session/module.go:160 +0x1a0

```

**Comment by evilsocket** [comment]
can I have your `get *` output?

**Comment by strasharo** [comment]
Sure:
https://gist.githubusercontent.com/strasharo/84ba01f024644e198748be77bb27fbf0/raw/cfe3e1913c3c5e7a129d59eb1b8de240c4135e8c/gistfile1.txt

**Comment by strasharo** [comment]
Thanks @evilsocket , it's working now.
