### ISSUE TITLE
crash when wifi.recon on

### ISSUE THREAD

**Issue by tonjo** [bettercap/bettercap#452]
&#x2713; Ok with Prerequisites.

bettercap will crash after a few seconds when `wifi.recon on`.
Ubuntu 18.04, 2 wifi card tested.

### Environment

* Bettercap version you are using: **2.16, from `go get -u` moments before filing the issue**
* OS version and architecture you are using. **PC Dell G3 17'' with Ubuntu 18.04, tested cards:**
    - Intel Corporation Device a370 (rev 10)  (as seen by lspci and lshw)
    - Atheros AR9271 via USB (Alfa)

* Go version if building from sources. From apt install: 

    $ go version
    go version go1.11.5 linux/amd64

* Command line arguments you are using. `bettercap -iface wloX -no-colors -debug`
* Caplet code you are using or the interactive session commands.
* **Full debug output** while reproducing the issue ( `bettercap -debug ...` ).

### Steps to Reproduce

1. Execute bettercap
2. wifi.recon on
3. Wait a few seconds

**Expected behavior:** 
Wifi discovery and handshake capture.

**Actual behavior:**
Crash 

~~[betterbug.log](https://github.com/bettercap/bettercap/files/2877580/betterbug.log)~~

```
# bettercap -iface wloX -no-colors -debug
bettercap v2.16 (type 'help' for a list of commands)

 wloX  » [23:28:47] [sys.log] [dbg] FindGateway(wloX) [cmd=ip opts=[route] parser=^(default|[0-9]+\.[0-9]+\.[0-9]+\.[0-9]+)\svia\s([0-9]+\.[0-9]+\.[0-9]+\.[0-9]+)\sdev\s(\S+).*$]
 wloX  » [23:28:47] [sys.log] [dbg] FindGateway(wloX) output:
default via 192.168.0.1 dev wlo1 proto dhcp metric 600 
169.254.0.0/16 dev wlo1 scope link metric 1000 
192.168.0.0/24 dev wlo1 proto kernel scope link src 192.168.0.125 metric 600
 wloX  » [23:28:47] [sys.log] [dbg] FindGateway(wloX): nothing found :/
 wloX  » [23:28:47] [sys.log] [dbg] Could not detect gateway.
 wloX  » [23:28:47] [session.started] {session.started 2019-02-18 23:28:47.350072985 +0100 CET m=+0.038004026 <nil>}
 wloX  » [23:28:47] [mod.started] events.stream
 wloX  » [23:28:47] [mod.started] net.recon
 wloX  » wifi.recon on
[23:28:53] [sys.log] [dbg] wifi wifi supported frequencies: [2412 2417 2422 2427 2432 2437 2442 2447 2452 2457 2462 2467 2472]
[23:28:53] [sys.log] [inf] wifi started (min rssi: -200 dBm)
[23:28:53] [mod.started] wifi
 wloX  » [23:28:53] [sys.log] [inf] wifi channel hopper started.
 wloX  » [23:28:53] [sys.log] [dbg] wifi hopping on channel 1
 wloX  » [23:28:53] [sys.log] [dbg] wifi wifi stations pruner started.
 wloX  » [23:28:53] [sys.log] [dbg] wifi hopping on channel 2
 wloX  » [23:28:53] [wifi.ap.new] wifi access point FASTWEB-D69A0B (-78 dBm) detected as x:x:x (Technicolor).
 wloX  » [23:28:54] [sys.log] [dbg] wifi hopping on channel 3
 wloX  » [23:28:54] [sys.log] [dbg] wifi hopping on channel 4
 wloX  » [23:28:54] [sys.log] [dbg] wifi hopping on channel 5
 wloX  » panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x9c8ca3]

goroutine 98 [running]:
github.com/bettercap/bettercap/vendor/github.com/evilsocket/islazy/data.(*UnsortedKV).Get(0x0, 0xc0006cbe20, 0x11, 0x0, 0x0, 0x0)
    /home/tonjo/go/src/github.com/bettercap/bettercap/vendor/github.com/evilsocket/islazy/data/unsortedkv.go:84 +0x33
github.com/bettercap/bettercap/vendor/github.com/evilsocket/islazy/data.(*UnsortedKV).GetOr(0x0, 0xc0006cbe20, 0x11, 0x0, 0x0, 0xfaa360, 0xc0005e4200)
    /home/tonjo/go/src/github.com/bettercap/bettercap/vendor/github.com/evilsocket/islazy/data/unsortedkv.go:93 +0x3f
github.com/bettercap/bettercap/network.(*LAN).GetAlias(0xc0005a4b00, 0xc0006cbe20, 0x11, 0xc0006cbe20, 0x11)
    /home/tonjo/go/src/github.com/bettercap/bettercap/network/lan.go:230 +0x4b
github.com/bettercap/bettercap/modules/wifi.(*WiFiModule).discoverProbes(0xc000492480, 0xc00062c280, 0xc0006b8780, 0x1236f60, 0xc000614b00)
    /home/tonjo/go/src/github.com/bettercap/bettercap/modules/wifi/wifi_recon.go:113 +0x17a
github.com/bettercap/bettercap/modules/wifi.(*WiFiModule).Start.func1()
    /home/tonjo/go/src/github.com/bettercap/bettercap/modules/wifi/wifi.go:471 +0x28c
created by github.com/bettercap/bettercap/session.(*SessionModule).SetRunning
    /home/tonjo/go/src/github.com/bettercap/bettercap/session/module.go:200 +0x1a1
```

**Comment by evilsocket** [comment]
What if you delete the `/root/bettercap.aliases` file and retry?

**Comment by tonjo** [comment]
Yep, that definitely did the trick.
