### ISSUE TITLE
implement ble.* module

### ISSUE THREAD

**Issue by evilsocket** [bettercap/bettercap#74]
A `bleah` kind of thing but cooler.

**Comment by evilsocket** [comment]
Developement of this feature is [work in progress](https://github.com/bettercap/bettercap/tree/ble.discover).

**Comment by Neal** [comment]
I know this is still WIP, but wanted to point out of a runtime error when turning on `ble.recon` on macOS 10.13.3. Relevant logs:

```
❯ ble.recon on
panic: runtime error: cgo argument has Go pointer to Go pointer

goroutine 1 [running]:
github.com/bettercap/gatt/xpc.XpcConnect.func2(0x5502dd0, 0xc4202f8740, 0x5502dd0)
	/Users/neal/go/src/github.com/bettercap/gatt/xpc/xpc_darwin.go:169 +0x96
github.com/bettercap/gatt/xpc.XpcConnect(0x46b1791, 0xf, 0x4b45660, 0xc4200b6080, 0x0)
	/Users/neal/go/src/github.com/bettercap/gatt/xpc/xpc_darwin.go:169 +0xbd
github.com/bettercap/gatt.NewDevice(0x4b8baf8, 0x1, 0x1, 0xc420000180, 0x4709cb0, 0xc420492000, 0xc4200001a8)
	/Users/neal/go/src/github.com/bettercap/gatt/device_darwin.go:67 +0x227
github.com/bettercap/bettercap/modules.(*BLERecon).Configure(0xc420378ae0, 0xc42032ec00, 0xc)
	/Users/neal/go/src/github.com/bettercap/bettercap/modules/ble_recon.go:79 +0x95
github.com/bettercap/bettercap/modules.(*BLERecon).Start(0xc420378ae0, 0x1, 0x0)
	/Users/neal/go/src/github.com/bettercap/bettercap/modules/ble_recon.go:122 +0x4c
github.com/bettercap/bettercap/modules.NewBLERecon.func1(0x0, 0x0, 0x0, 0x1, 0x0)
	/Users/neal/go/src/github.com/bettercap/bettercap/modules/ble_recon.go:45 +0x2a
github.com/bettercap/bettercap/session.(*Session).Run(0xc4200cc0f0, 0xc42032ecd0, 0xc, 0x1, 0x1)
	/Users/neal/go/src/github.com/bettercap/bettercap/session/session.go:483 +0x2d9
main.main()
	/Users/neal/go/src/github.com/bettercap/bettercap/main.go:97 +0x122f
```

**Comment by evilsocket** [comment]
@Neal fixed by https://github.com/bettercap/gatt/commits?author=evilsocket

**Comment by Neal** [comment]
@evilsocket pulled in latest codes and now the `ble.recon on` command doesn't finish (I don't get the prompt back and no debug logs)

**Comment by evilsocket** [comment]
can you just let me finish this module?

**Comment by evilsocket** [comment]
Modules completed for Linux, macOS support is incomplete for now, the [GATT library](https://github.com/bettercap/gatt) doesn't seem to work correctly on High Sierra (it hangs due to some unhandle XPC messages).

**Comment by okazymyrov** [comment]
I get the following results on macOS 10.15, MacBook Pro (15-inch, 2018):
![image](https://user-images.githubusercontent.com/1721372/67373943-c1f21e80-f580-11e9-9496-fbadea905d00.png)

`ble.recon on` works, but returns wrong MACs.

**Comment by hmeine** [comment]
From what I can see from these old issues and PR discussions, https://github.com/bettercap/gatt/issues/1 has been closed as "completed" on 2019-09-08, after https://github.com/bettercap/gatt/pull/10 was merged. However, that does not seem to have fixed the issue, as @evilsocket and @raff discussed. Both of them seem to have made further progress in the gatt fork at https://github.com/raff/gatt/tree/master (one commit each) immediately after, and these commits also appear in https://github.com/bettercap/gatt/commits/master/. However, I am not sure how the exact status is:
* This issue is still open, but it also has a generic title, so it may not be good to close until *all* bugs are fixed.
* I am still seeing the hang when trying to `ble.recon on`, but I am on MacOS 14.5 (on an ARM MBP), so I am not sure if it is still the same hang or a new one. There seeem to be recent reports from others seeing the same (#1026, #1065 for instance).
* According to the screenshots, @evilsocket and @okazymyrov seem to have gotten `ble.recon` to work except for proper MAC addresses, but that was five years ago. Given that the commits seem to be in bettercap's gatt repo, I would naively have expected that to be the state that I should also have gotten, but I could not reproduce that. (But that could also be related to 5 years of MacOS API changes, CPU / hardware architecture changes, or the fact that I am just using the MacPorts build.)

**Comment by evilsocket** [comment]
@hmeine the bottom line is that macOS API change so quickly (specifically the dictionaries being sent on macOS IPC) that it is not possible to keep the gatt package updated

**Comment by hmeine** [comment]
I see. I just found #769 where you stated a similar conclusion. I guess it's good to have this (sad) summary also here.

**Comment by raff** [comment]
Note that 4 years ago I gave up trying to keep my package (github.com/raff/goble) in a workable state. And there are now official APIs for Bluetooth on MacOS (CoreBluetooth). 

I see that this package has bindings for Go: https://github.com/JuulLabs-OSS/cbgo (I think originally they also used my xpc stuff). Maybe you can update to use this.
