### ISSUE TITLE
panic during JSON serialization

### ISSUE THREAD

**Issue by slingamn** [bettercap/bettercap#868]
This is a derivative of bettercap 3ac520c744ee3f9e, with go 1.16, on armv7l.

```
Thu Apr 22 21:01:50 2021 daemon.err bettercap[8646]: panic: runtime error: invalid memory address or nil pointer dereference [recovered]
Thu Apr 22 21:01:50 2021 daemon.err bettercap[8646]:    panic: runtime error: invalid memory address or nil pointer dereference [recovered]
Thu Apr 22 21:01:50 2021 daemon.err bettercap[8646]:    panic: runtime error: invalid memory address or nil pointer dereference
Thu Apr 22 21:01:50 2021 daemon.err bettercap[8646]: [signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x1970c0]
Thu Apr 22 21:01:50 2021 daemon.err bettercap[8646]:
Thu Apr 22 21:01:50 2021 daemon.err bettercap[8646]: goroutine 113 [running]:
Thu Apr 22 21:01:50 2021 daemon.err bettercap[8646]: encoding/json.(*encodeState).marshal.func1(0x2952d48)
Thu Apr 22 21:01:50 2021 daemon.err bettercap[8646]:    encoding/json/encode.go:328 +0x80
Thu Apr 22 21:01:50 2021 daemon.err bettercap[8646]: panic(0x839728, 0xfb1418)
Thu Apr 22 21:01:50 2021 daemon.err bettercap[8646]:    runtime/panic.go:965 +0x174
Thu Apr 22 21:01:50 2021 daemon.err bettercap[8646]: encoding/json.(*encodeState).marshal.func1(0x2952b54)
Thu Apr 22 21:01:50 2021 daemon.err bettercap[8646]:    encoding/json/encode.go:328 +0x80
Thu Apr 22 21:01:50 2021 daemon.err bettercap[8646]: panic(0x839728, 0xfb1418)
Thu Apr 22 21:01:50 2021 daemon.err bettercap[8646]:    runtime/panic.go:965 +0x174
Thu Apr 22 21:01:50 2021 daemon.err bettercap[8646]: encoding/json.(*encodeState).string(0x2988180, 0x0, 0x4, 0x1)
Thu Apr 22 21:01:50 2021 daemon.err bettercap[8646]:    encoding/json/encode.go:1033 +0x4c
Thu Apr 22 21:01:50 2021 daemon.err bettercap[8646]: encoding/json.stringEncoder(0x2988180, 0x80bb38, 0x2857fa0, 0x198, 0x100)
Thu Apr 22 21:01:50 2021 daemon.err bettercap[8646]:    encoding/json/encode.go:647 +0x154
Thu Apr 22 21:01:50 2021 daemon.err bettercap[8646]: encoding/json.structEncoder.encode(0x2958000, 0x13, 0x20, 0x28968e0, 0x2988180, 0x8c5058, 0x2823860, 0x99, 0x8c0100)
Thu Apr 22 21:01:50 2021 daemon.err bettercap[8646]:    encoding/json/encode.go:761 +0x1fc
Thu Apr 22 21:01:50 2021 daemon.err bettercap[8646]: encoding/json.(*encodeState).reflectValue(0x2988180, 0x8c5058, 0x2823860, 0x99, 0x2980100)
Thu Apr 22 21:01:50 2021 daemon.err bettercap[8646]:    encoding/json/encode.go:360 +0x68
Thu Apr 22 21:01:50 2021 daemon.err bettercap[8646]: encoding/json.(*encodeState).marshal(0x2988180, 0x8c5058, 0x2823860, 0x2950100, 0x0, 0x0)
Thu Apr 22 21:01:50 2021 daemon.err bettercap[8646]:    encoding/json/encode.go:332 +0xe8
Thu Apr 22 21:01:50 2021 daemon.err bettercap[8646]: encoding/json.Marshal(0x8c5058, 0x2823860, 0x8c5058, 0x2823860, 0x199554, 0x95144, 0x94d1c)
Thu Apr 22 21:01:50 2021 daemon.err bettercap[8646]:    encoding/json/encode.go:161 +0x40
Thu Apr 22 21:01:50 2021 daemon.err bettercap[8646]: github.com/bettercap/bettercap/network.(*AccessPoint).MarshalJSON(0x285d140, 0x0, 0x0, 0x0, 0x0, 0x0)
Thu Apr 22 21:01:50 2021 daemon.err bettercap[8646]:    github.com/bettercap/bettercap/network/wifi_ap.go:48 +0x1dc
Thu Apr 22 21:01:50 2021 daemon.err bettercap[8646]: encoding/json.marshalerEncoder(0x279c2a0, 0x8d4768, 0x285d140, 0x16, 0x2850100)
Thu Apr 22 21:01:50 2021 daemon.err bettercap[8646]:    encoding/json/encode.go:479 +0x88
Thu Apr 22 21:01:50 2021 daemon.err bettercap[8646]: encoding/json.(*encodeState).reflectValue(0x279c2a0, 0x8d4768, 0x285d140, 0x16, 0x2850100)
Thu Apr 22 21:01:50 2021 daemon.err bettercap[8646]:    encoding/json/encode.go:360 +0x68
Thu Apr 22 21:01:50 2021 daemon.err bettercap[8646]: encoding/json.interfaceEncoder(0x279c2a0, 0x80b448, 0x29566dc, 0x94, 0x100)
Thu Apr 22 21:01:50 2021 daemon.err bettercap[8646]:    encoding/json/encode.go:716 +0x88
Thu Apr 22 21:01:50 2021 daemon.err bettercap[8646]: encoding/json.structEncoder.encode(0x29c6120, 0x3, 0x4, 0x29c2240, 0x279c2a0, 0x8759f0, 0x29566c0, 0x99, 0x870100)
Thu Apr 22 21:01:50 2021 daemon.err bettercap[8646]:    encoding/json/encode.go:761 +0x1fc
Thu Apr 22 21:01:50 2021 daemon.err bettercap[8646]: encoding/json.(*encodeState).reflectValue(0x279c2a0, 0x8759f0, 0x29566c0, 0x99, 0x2790100)
Thu Apr 22 21:01:50 2021 daemon.err bettercap[8646]:    encoding/json/encode.go:360 +0x68
Thu Apr 22 21:01:50 2021 daemon.err bettercap[8646]: encoding/json.(*encodeState).marshal(0x279c2a0, 0x8759f0, 0x29566c0, 0x2950100, 0x0, 0x0)
Thu Apr 22 21:01:50 2021 daemon.err bettercap[8646]:    encoding/json/encode.go:332 +0xe8
Thu Apr 22 21:01:50 2021 daemon.err bettercap[8646]: encoding/json.Marshal(0x8759f0, 0x29566c0, 0x8759f0, 0x29566c0, 0x1b530, 0x5b934, 0x5c888)
Thu Apr 22 21:01:50 2021 daemon.err bettercap[8646]:    encoding/json/encode.go:161 +0x40
Thu Apr 22 21:01:50 2021 daemon.err bettercap[8646]: github.com/bettercap/bettercap/modules/api_rest.(*RestAPI).streamEvent(0x257b770, 0x27aa000, 0x9391ca, 0xb, 0xb00757f4, 0xc01896ef, 0xf821ab6c, 0x29, 0x100f800, 0x8d4768, ...)
Thu Apr 22 21:01:50 2021 daemon.err bettercap[8646]:    github.com/bettercap/bettercap/modules/api_rest/api_rest_ws.go:24 +0x48
Thu Apr 22 21:01:50 2021 daemon.err bettercap[8646]: github.com/bettercap/bettercap/modules/api_rest.(*RestAPI).streamWriter(0x257b770, 0x27aa000, 0xb02c0c, 0x29cc000, 0x29c8100)
Thu Apr 22 21:01:50 2021 daemon.err bettercap[8646]:    github.com/bettercap/bettercap/modules/api_rest/api_rest_ws.go:81 +0x260
Thu Apr 22 21:01:50 2021 daemon.err bettercap[8646]: created by github.com/bettercap/bettercap/modules/api_rest.(*RestAPI).startStreamingEvents
Thu Apr 22 21:01:50 2021 daemon.err bettercap[8646]:    github.com/bettercap/bettercap/modules/api_rest/api_rest_ws.go:116 +0x1f8
```

This seems related to #803. Given the last line in the Go source before the panic:

https://github.com/golang/go/blob/9baddd3f21230c55f0ad2a10f5f20579dcf0a0bb/src/encoding/json/encode.go#L1033

it seems like this may be caused by a data race?

Thanks for your time.

**Comment by evilsocket** [comment]
not related to that issue, in this case it panic'ed because something was nil ... specifically it happened here https://github.com/bettercap/bettercap/blob/3ac520c744ee3f9eadea57683c692a7bbf8476d1/modules/api_rest/api_rest_ws.go#L24 ... do you happen to know what was the last event printed on the events stream before this panic?

**Comment by slingamn** [comment]
It was probably a `wifi.ap.new` but I'm not entirely sure.

The reason I think it's a data race is:

1. It happened inside [json.Marshal](https://golang.org/pkg/encoding/json/#Marshal); the contract for `json.Marshal` makes it sound like it should handle nil pointer and interface values without issue.
2. The specific line that panicked (`encode.go:1033` in go1.16.3, linked above) is just a byte index into a string. Even though such a thing would be surprising, it seems to me that the only thing that could cause this is a pointer-length mismatch in the string struct caused by a data race, as described [here](https://research.swtch.com/gorace).

**Comment by evilsocket** [comment]
maybe, to be honest i'm not sure, most of the race conditions i've experienced in bettercap panic with a "concurrent access to map yada yada" error, but there could be definitely other conditions that present different behaviour

i was asking about the events because i introduced some new ones recently and i thought maybe i forgot to validate some pointer :D

**Comment by slingamn** [comment]
Yeah, this one really surprises me because whenever I've seen a data race cause panics in the past, it's always been map access. The time window in which a map access race can occur is arbitrarily large (as long as it takes to iterate over the map), whereas the window for these should be very small.

But the panicking line appears to be an actual violation of Go's memory safety properties --- a string index that panics with a nil dereference, instead of "index out of range" --- so the only explanation I can think of is a data race.

**Comment by evilsocket** [comment]
makes sense

**Comment by slingamn** [comment]
Just curious, do you know which commit resolved this?
